services:
  file-storage:
    build: ./file-storage
    container_name: file-storage
    ports:
      - "8080:8080"
    env_file:
      - "file-storage/.env"
    volumes:
      - file-storage-data:/var/lib/docker/volumes/file-storage-data
    depends_on:
      file-storage-db:
          condition: service_healthy
          restart: true

  file-storage-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file-storage-db
      PGDATA: /var/lib/postgresql/data/file-storage-pgdata
    ports:
      - "5432:5432"
    volumes:
      - file-storage-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 3

  file-analysis:
    build: ./file-analysis
    container_name: file-analysis
    ports:
      - "8081:8080"
    env_file:
      - "file-analysis/.env"
    depends_on:
      - file-storage

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - "api-gateway/.env"
    depends_on:
      - file-storage
      - file-analysis

volumes:
  file-storage-data:
    driver: local

  file-storage-pgdata:
#    driver: local